from .globals import (
    DETECTION_MODEL_DEVICES,
    CLASSIFICATION_MODEL_DEVICES,
    SEGMENTATION_MODEL_DEVICES,
    EASYOCR_DEVICES,
)

from .modelpaths import (
    DETECTION_MODEL_PATH,
    CLASSIFICATION_MODEL_PATH,
    SEGMENTATION_MODEL_PATH,
)

__all__ = [
    "CLASSIFICATION_MODEL_DEVICES",
    "DETECTION_MODEL_DEVICES",
    "SEGMENTATION_MODEL_DEVICES",
    "EASYOCR_DEVICES",
    "DETECTION_MODEL_PATH",
    "CLASSIFICATION_MODEL_PATH",
    "SEGMENTATION_MODEL_PATH",
]
