from .globals import DETECTION_MODEL_DEVICES, CLASSIFICATION_MODEL_DEVICES, SEGMENTATION_MODEL_DEVICES

__all__ = [
    "CLASSIFICATION_MODEL_DEVICES",
    "DETECTION_MODEL_DEVICES",
    "SEGMENTATION_MODEL_DEVICES",
]