# The default parameters and settings for the debug view
# GENERAL
APP_TITLE = "Debug Viewer for AETD"

# DIRECTION_EXTRACTION
DIRECTION_EXTRACTION_CROP_TOP = 28
DIRECTION_EXTRACTION_CROP_BOTTOM = 900
DIRECTION_EXTRACTION_CROP_LEFT = 810
DIRECTION_EXTRACTION_CROP_RIGHT = 810
DIRECTION_EXTRACTION_RED_THRESHOLD = 150
DIRECTION_EXTRACTION_CONTOUR_MIN_AREA = 50
DIRECTION_EXTRACTION_CENTER_PILLAR_CROP = 140

# SPEED_EXTRACTION
SPEED_EXTRACTION_CROP_TOP = 5
SPEED_EXTRACTION_CROP_BOTTOM = 1057
SPEED_EXTRACTION_CROP_LEFT = 770
SPEED_EXTRACTION_CROP_RIGHT = 1125
SPEED_EXTRACTION_EASYOCR_DEVICES = False  # True = GPU
SPEED_EXTRACTION_SHARPEN_AMOUNT = 1.5

# ROADOBJECT_EXTRACTION
ROADOBJECT_EXTRACTION_CROP_TOP = 160
DETECTION_MODEL_PATH = "models/yolo-detect-m_best_epochs-100_size-460-960_05-08-2025.pt"
DETECTION_MODEL_DEVICES = "cpu"
CLASSIFICATION_MODEL_PATH = "models/yolo-cls-s_best_epochs-30_size-32-32_06-08-2025.pt"
CLASSIFICATION_MODEL_DEVICES = "cpu"

# ROADSEGMENT_EXTRACTION
ROADSEGMENT_EXTRACTION_CROP_TOP = 160
SEGMENTATION_MODEL_PATH = (
    "models/yolo-seg-m_full-road_best_epochs-300_size-460-960_07-08-2025.pt"
)
SEGMENTATION_MODEL_DEVICES = "cpu"
ROADSEGMENT_EXTRACTION_MIN_CONF = 0.6
ROADSEGMENT_EXTRACTION_MIN_AREA_LANE = 400
ROADSEGMENT_EXTRACTION_MIN_LENGTH_LANE = 300
ROADSEGMENT_EXTRACTION_MIN_AREA_DRIVEABLE = 1000
ROADSEGMENT_EXTRACTION_MIN_LENGTH_DRIVEABLE = 1000

# PREPROCESSING
PREPROCESSING_SHARPEN_AMOUNT = 1.5
PREPROCESSING_GAMMA_MAX = 1.5
PREPROCESSING_CLAHE_THRESHOLD = 50
